---
debug_enabled_default: true
update_default: true
reboot_default: true
server_update_reboot_pre_delay: 5
server_update_reboot_pre_reboot_delay: 60
server_update_reboot_post_reboot_delay: 180
server_update_reboot_reboot_timeout: 1200
#
#For Redhat/CentOS: List of packages to not update (comma separated).
#Can include wildcard to match multiple packages.
#server_update_yum_exclude_pkgs: "mysql*, bash, openssh*"
server_update_yum_exclude_pkgs: "docker*"
#
#For Redhat/CentOS: List of packages to ONLY update (comma separated).
#Can include wildcard to match multiple packages.
#This will not update anything else (besides dependencies). '*' will update all installed packages.
#server_update_yum_install_pkgs: "kernel-*, iwl*firmware, microcode_ctl, dracut"
server_update_yum_install_pkgs: '*'
